import { Button, LoadingOverlay, Stack, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { useCallback, useState } from "react";
import { CommandHelper } from "../../utils/CommandHelper";
import ConsoleWrapper from "../ConsoleWrapper/ConsoleWrapper";
import { UserGuide } from "../UserGuide/UserGuide";
import React from "react";
import { SaveOutputToTextFile_v2 } from "../SaveOutputToFile/SaveOutputToTextFile";
import { LoadingOverlayAndCancelButton } from "../OverlayAndCancelButton/OverlayAndCancelButton";
import { Dropper } from "../FileHandler/Dropper";
import { generateFilePath } from "../FileHandler/FileHandler";

const title = "Rainbowcrack";
const description_userguide =
    "RainbowCrack is a computer program which generates rainbow tables to be used in password cracking . " +
    "This is a dictionary-based attack that takes place upon a web server and will analyse the PLACEHOLDER " +
    "results within this process.\n\nHow to use Dirb:\n\nStep 1: Enter a valid URL.\n PLACEHOLDER" +
    "       E.g. https://www.deakin.edu.au\n\nStep 2: Enter a file directory pathway to access PLACEHOLDER" +
    "a wordlist\n       E.g. home/wordlist/wordlist.txt\n\nStep 3: Click Scan to commence " +
    "the Dirb operation.\n\nStep 4: View the Output block below to view the results of the tool's execution.";

interface FormValues {
    hashcode: string;
}

export function rcrack() {
    const [loading, setLoading] = useState(false);
    const [output, setOutput] = useState("");
    const [pid, setPid] = useState("");
    const [allowSave, setAllowSave] = useState(false);
    const [hasSaved, setHasSaved] = useState(false);
    const [fileNames, setFileNames] = useState<string[]>([]);

    let form = useForm({
        initialValues: {
            hashcode: "",
        },
    });

    // Uses the callback function of runCommandGetPidAndOutput to handle and save data
    // generated by the executing process into the output state variable.
    const handleProcessData = useCallback((data: string) => {
        setOutput((prevOutput) => prevOutput + "\n" + data); // Update output
    }, []);

    // Uses the onTermination callback function of runCommandGetPidAndOutput to handle
    // the termination of that process, resetting state variables, handling the output data,
    // and informing the user.
    const handleProcessTermination = useCallback(
        ({ code, signal }: { code: number; signal: number }) => {
            if (code === 0) {
                handleProcessData("\nProcess completed successfully.");
            } else if (signal === 15) {
                handleProcessData("\nProcess was manually terminated.");
            } else {
                handleProcessData(`\nProcess terminated with exit code: ${code} and signal code: ${signal}`);
            }
            // Clear the child process pid reference
            setPid("");
            // Cancel the Loading Overlay
            setLoading(false);

            // Allow Saving as the output is finalised
            setAllowSave(true);
            setHasSaved(false);
        },
        [handleProcessData]
    );

    // Actions taken after saving the output
    const handleSaveComplete = () => {
        // Indicating that the file has saved which is passed
        // back into SaveOutputToTextFile to inform the user
        setHasSaved(true);
        setAllowSave(false);
    };

    const onSubmit = async (values: FormValues) => {
        // Disallow saving until the tool's execution is complete
        setAllowSave(false);

        // Start the Loading Overlay
        setLoading(true);
        const args = ["."];

        if (fileNames.length === 0) {
            args.push("-h", values.hashcode);
        } else {
            const filePath = generateFilePath("Rainbowcrack");
            const dataUploadPath = filePath + "/" + fileNames[0];
            args.push("-l", dataUploadPath);
        }

        //This is the old version for runCommand
        //const output = await CommandHelper.runCommand("rcrack", args);
        //setOutput(output);
        //setLoading(false);

        try {
            const result = await CommandHelper.runCommandGetPidAndOutput(
                "rcrack",
                args,
                handleProcessData,
                handleProcessTermination
            );
            setPid(result.pid);
            setOutput(result.output);
        } catch (e: any) {
            setOutput(e.message);
        }
    };

    const clearOutput = useCallback(() => {
        setOutput("");
        setHasSaved(false);
        setAllowSave(false);
    }, [setOutput]);

    return (
        <form onSubmit={form.onSubmit((values) => onSubmit(values))}>
            {LoadingOverlayAndCancelButton(loading, pid)}
            <Stack>
                {UserGuide(title, description_userguide)}
                <TextInput
                    label={"Enter the Hash code"}
                    required
                    disabled={fileNames.length > 0}
                    value={fileNames.length > 0 ? "" : form.values.hashcode}
                    onChange={(event) => {
                        if (fileNames.length === 0) {
                            form.setFieldValue("hashcode", event.currentTarget.value);
                        }
                    }}
                />
                <Dropper
                    fileNames={fileNames}
                    setFileNames={setFileNames}
                    maxFileNum={1}
                    componentName="Rainbowcrack"
                />
                <Button type={"submit"}>Crack</Button>
                {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
                <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
            </Stack>
        </form>
    );
}
export default rcrack;
