import { Alert, Button, NativeSelect, Stack, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { useCallback, useState ,useEffect} from "react";
import { CommandHelper } from "../../utils/CommandHelper";
import ConsoleWrapper from "../ConsoleWrapper/ConsoleWrapper";
import { RenderComponent } from "../UserGuide/UserGuide";
import { SaveOutputToTextFile_v2 } from "../SaveOutputToFile/SaveOutputToTextFile";
import { LoadingOverlayAndCancelButtonPkexec } from "../OverlayAndCancelButton/OverlayAndCancelButton";
import { checkAllCommandsAvailability } from "../../utils/CommandAvailability";
import InstallationModal from "../InstallationModal/InstallationModal";

interface FormValuesType {
    url: string;
    userAgent: string;
    worker: number;
    sockets: number;
    method: string;
    sslCheck: string;
}

const dosHttpMethod = ["get", "post", "random"];
const sslCheckStatus = ["Yes", "No"];

const GoldenEye = () => {
    const [loading, setLoading] = useState(false);
    const [output, setOutput] = useState("");
    const [pid, setPid] = useState("");
    const [allowSave, setAllowSave] = useState(false);
    const [hasSaved, setHasSaved] = useState(false);
    const [selectedMethod, setSelectedMethod] = useState("");
    const [selectedSslCheck, setSelectedSslCheck] = useState("");
    const [isCommandAvailable, setIsCommandAvailable] = useState(false); 
    const [loadingModal, setLoadingModal] = useState(true);
    const [opened, setOpened] = useState(!isCommandAvailable);

    // Component Constants.
    const title = "Goldeneye"; // Title of the component.
    const description = "GoldenEye is a HTTP DoS Test Tool. This tool can be used to test if a site is susceptible to Deny of Service (DoS) attacks. Is possible to open several parallel connections against a URL to check if the web server can be compromised"; // Description of the component.
    const steps =
        "Step 1: Enter a valid URL of the target.\n" +
        "Step 2: Enter any additional options for the scan.\n" +
        "Step 3: Enter any additional parameters for the scan.\n" +
        "Step 4: Click Scan to commence GoldenEye's operation.\n" +
        "Step 5: View the Output block below to view the results of the tool's execution.";
    const sourceLink = "https://www.kali.org/tools/goldeneye/"; // Link to the source code (or Kali Tools).
    const tutorial = ""; // Link to the official documentation/tutorial.
    const dependencies = ["python3"] // Contains the dependencies required by the component.

    let form = useForm({
        initialValues: {
            url: "",
            userAgent: "",
            worker: 0,
            sockets: 0,
            method: "",
            sslCheck: "",
        },
    });

    // Check if the command is available and set the state variables accordingly.
    useEffect(() => {
        // Check if the command is available and set the state variables accordingly.
        checkAllCommandsAvailability(dependencies)
            .then((isAvailable) => {
                setIsCommandAvailable(isAvailable); // Set the command availability state
                setOpened(!isAvailable); // Set the modal state to opened if the command is not available
                setLoadingModal(false); // Set loading to false after the check is done
            })
            .catch((error) => {
                console.error("An error occurred:", error);
                setLoadingModal(false); // Also set loading to false in case of error
            });
    }, []);

    // Uses the callback function of runCommandGetPidAndOutput to handle and save data
    // generated by the executing process into the output state variable.
    const handleProcessData = useCallback((data: string) => {
        setOutput((prevOutput) => prevOutput + "\n" + data); // Update output
    }, []);

    // Uses the onTermination callback function of runCommandGetPidAndOutput to handle
    // the termination of that process, resetting state variables, handling the output data,
    // and informing the user.
    const handleProcessTermination = useCallback(
        ({ code, signal }: { code: number; signal: number }) => {
            if (code === 0) {
                handleProcessData("\nProcess completed successfully.");
            } else if (signal === 15) {
                handleProcessData("\nProcess was manually terminated.");
            } else {
                handleProcessData(`\nProcess terminated with exit code: ${code} and signal code: ${signal}`);
            }
            // Clear the child process pid reference
            setPid("");
            // Cancel the Loading Overlay
            setLoading(false);

            // Allow Saving as the output is finalised
            setAllowSave(true);
            setHasSaved(false);
        },
        [handleProcessData]
    );

    // Actions taken after saving the output
    const handleSaveComplete = () => {
        // Indicating that the file has saved which is passed
        // back into SaveOutputToTextFile to inform the user
        setHasSaved(true);
        setAllowSave(false);
    };

    const onSubmit = async (values: FormValuesType) => {
        setLoading(true);

        const args = [`/home/kali/Deakin-Detonator-Toolkit/src-tauri/exploits/Goldeneye/goldeneye.py`, `${values.url}`];

        values.userAgent ? args.push(`-u`, `${values.userAgent}`) : undefined;
        values.worker ? args.push(`-w`, `${values.worker}`) : undefined;
        values.sockets ? args.push(`-s`, `${values.sockets}`) : undefined;
        selectedMethod ? args.push(`-m`, selectedMethod) : undefined;
        selectedSslCheck === "No" ? args.push(`-n`) : undefined;

        try {
            const result = await CommandHelper.runCommandGetPidAndOutput(
                "python3",
                args,
                handleProcessData,
                handleProcessTermination
            );
            setPid(result.pid);
            setOutput(result.output);
        } catch (e: any) {
            setOutput(e.message);
        }
    };

    const clearOutput = useCallback(() => {
        setOutput("");
        setHasSaved(false);
        setAllowSave(false);
    }, [setOutput]);

    return (
        <RenderComponent
            title={title}
            description={description}
            steps={steps}
            tutorial={tutorial}
            sourceLink={sourceLink}
        >
            {!loadingModal && (
                <InstallationModal
                    isOpen={opened}
                    setOpened={setOpened}
                    feature_description={description}
                    dependencies={dependencies}
                ></InstallationModal>
            )}
            <form onSubmit={form.onSubmit(onSubmit)}>
            <Stack>
                {LoadingOverlayAndCancelButtonPkexec(loading, pid, handleProcessData, handleProcessTermination)}
                <TextInput
                    label={"Url of the target"}
                    placeholder={"Example: https://www.google.com"}
                    required
                    {...form.getInputProps("url")}
                />
                <TextInput
                    label={"List of user agents"}
                    placeholder={"Please enter filepath for the list of useragent"}
                    {...form.getInputProps("userAgent")}
                />
                <TextInput
                    label={"Number of concurrent workers"}
                    placeholder={"Please specify a number (Default = 10)"}
                    {...form.getInputProps("worker")}
                />
                <TextInput
                    label={"Number of concurrent sockets"}
                    placeholder={"Please specify a number (Default = 500)"}
                    {...form.getInputProps("sockets")}
                />
                <NativeSelect
                    value={selectedMethod}
                    onChange={(e) => setSelectedMethod(e.target.value)}
                    title={"HTTP Method"}
                    data={dosHttpMethod}
                    placeholder={"HTTP Method"}
                    description={"Please select type of HTTP request to flood server with"}
                />
                <NativeSelect
                    value={selectedSslCheck}
                    onChange={(e) => setSelectedSslCheck(e.target.value)}
                    title={"SSL Check"}
                    data={sslCheckStatus}
                    placeholder={"ssl Check"}
                    description={"Do you want to verify the ssl certificate"}
                />
                <Button type={"submit"}>Launch Dos Attack</Button>
                {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
                <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
            </Stack>
            </form>
        </RenderComponent>
    );
};

export default GoldenEye;
