import { Button, LoadingOverlay, NativeSelect, NumberInput, Stack, TextInput, Grid, Alert } from "@mantine/core";
import { useForm } from "@mantine/form";
import { IconAlertCircle } from "@tabler/icons";
import { useCallback, useState } from "react";
import { CommandHelper } from "../../utils/CommandHelper";
import ConsoleWrapper from "../ConsoleWrapper/ConsoleWrapper";
import { UserGuide } from "../UserGuide/UserGuide";
import { SaveOutputToTextFile_v2 } from "../SaveOutputToFile/SaveOutputToTextFile"; //v2

const title = "Hashcat";
const description_userguide =
    "Hashcat is an advanced password recovery tool that provides brute-force " +
    "attacks that are conducted with the hash values of passwords that are either " +
    "guessed or applied by the tool. DDT currently supports 3 " +
    "attack modes including Straight, Brute-force and Hybrid Wordlist + Mask.\n\n" +
    "A list of the Hashing Algorithm codes can be found at: https://hashcat.net/hashcat\n\n" +
    "How to use Hashcat:\n\n" +
    "Step 1: Pick an attack mode\n" +
    "       E.g. Straight\n\n" +
    "Step 2: Input hash type and hash algorithm code\n" +
    "       E.g. Hash Value, 2\n\n" +
    "Step 3: Input the hash value\n" +
    "       E.g. ae71a4222ef1893879b442f14c40c370\n\n" +
    "Step 4: Input password file.\n" +
    "        E.g. /root/pwd.txt\n\n" +
    "Step 5: Add additional commands as required, refer to weblink above.\n" +
    "       E.g. --force\n\n" +
    "Step 6: Click Scan to commence the Hashcat operation.\n\n" +
    "Step 7: View the Output block below to view the results";

interface FormValuesType {
    attackMode: string;
    inputType: string;
    maskCharsets: string;
    hashAlgorithmCode: number;
    hashValue: string;
    hashFilePath: string;
    passwordFilePath: string;
    additionalCommand: string;
    minPwdLen: number;
    maxPwdLen: number;
}

const inputType = ["Hash Value", "File"];
const attackMode = ["Straight", "Brute-force", "Hybride Wordlist + Mask"];

const Hashcat = () => {
    const [loading, setLoading] = useState(false);
    const [output, setOutput] = useState("");
    const [selectedModeOption, setSelectedModeOption] = useState("");
    const [selectedInputOption, setSelectedInputOption] = useState("");
    const [pid, setPid] = useState("");
    const [allowSave, setAllowSave] = useState(false);
    const [hasSaved, setHasSaved] = useState(false);

    let form = useForm({
        initialValues: {
            attackMode: "",
            inputType: "",
            maskCharsets: "",
            hashAlgorithmCode: 0,
            hashValue: "",
            hashFilePath: "",
            passwordFilePath: "",
            additionalCommand: "",
            minPwdLen: 1,
            maxPwdLen: 1,
        },
    });

    // Uses the callback function of runCommandGetPidAndOutput to handle and save data
    // generated by the executing process into the output state variable.
    const handleProcessData = useCallback((data: string) => {
        setOutput((prevOutput) => prevOutput + "\n" + data); // Update output
    }, []);
    // Uses the onTermination callback function of runCommandGetPidAndOutput to handle
    // the termination of that process, resetting state variables, handling the output data,
    // and informing the user.
    const handleProcessTermination = useCallback(
        ({ code, signal }: { code: number; signal: number }) => {
            if (code === 0) {
                handleProcessData("\nProcess completed successfully.");
            } else if (signal === 15) {
                handleProcessData("\nProcess was manually terminated.");
            } else {
                handleProcessData(`\nProcess terminated with exit code: ${code} and signal code: ${signal}`);
            }
            // Clear the child process pid reference
            setPid("");
            // Cancel the Loading Overlay
            setLoading(false);
            // Allow Saving as the output is finalised
            setAllowSave(true);
            setHasSaved(false);
        },
        [handleProcessData]
    );
    // Sends a SIGTERM signal to gracefully terminate the process
    const handleCancel = () => {
        if (pid !== null) {
            const args = [`-15`, pid];
            CommandHelper.runCommand("kill", args);
        }
    };

    const onSubmit = async (values: FormValuesType) => {
        setLoading(true);

        // Disallow saving until the tool's execution is complete
        setAllowSave(false);

        const args = [`-m${values.hashAlgorithmCode}`];
        if (selectedModeOption === "Straight") {
            args.push(`-a0`);
        } else if (selectedModeOption === "Brute-force") {
            args.push(`-a3`);
        } else if (selectedModeOption === "Hybride Wordlist + Mask") {
            args.push(`-a6`);
        }
        if (selectedInputOption === "Hash Value") {
            args.push(`${values.hashValue}`);
        } else if (selectedInputOption === "File") {
            args.push(`${values.hashFilePath}`);
        }
        if (selectedModeOption === "Straight") {
            args.push(`${values.passwordFilePath}`);
        } else if (selectedModeOption === "Brute-force") {
            args.push(`--increment`);
            args.push(
                `--increment`,
                `--increment-min`,
                `${values.minPwdLen}`,
                `--increment-max`,
                `${values.maxPwdLen}`
            );
            if (values.maskCharsets) {
                args.push(`${values.maskCharsets}`);
            }
        } else if (selectedModeOption === "Hybride Wordlist + Mask") {
            args.push(`${values.passwordFilePath}`);
            args.push(
                `--increment`,
                `--increment-min`,
                `${values.minPwdLen}`,
                `--increment-max`,
                `${values.maxPwdLen}`
            );
            if (values.maskCharsets) {
                args.push(`${values.maskCharsets}`);
            }
        }
        if (values.additionalCommand) {
            args.push(`${values.additionalCommand}`);
        }

        try {
            const result = await CommandHelper.runCommandGetPidAndOutput(
                "hashcat",
                args,
                handleProcessData,
                handleProcessTermination
            );
            setPid(result.pid);
            setOutput(result.output);
        } catch (e: any) {
            setOutput(e.message);
            setAllowSave(true);
        }
    };

    const clearOutput = useCallback(() => {
        setOutput("");
        setHasSaved(false);
        setAllowSave(false);
    }, [setOutput]);

    const isPasswordFile = selectedModeOption === "Straight" || selectedModeOption === "Hybride Wordlist + Mask";
    const isCharset = selectedModeOption === "Brute-force" || selectedModeOption === "Hybride Wordlist + Mask";
    const isFile = selectedInputOption == "File";

    const handleSaveComplete = () => {
        // Indicating that the file has saved which is passed
        // back into SaveOutputToTextFile to inform the user
        setHasSaved(true);
        setAllowSave(false);
    };

    return (
        <form
            onSubmit={form.onSubmit((values) =>
                onSubmit({ ...values, attackMode: selectedModeOption, inputType: selectedInputOption })
            )}
        >
            <LoadingOverlay visible={loading} />
            {loading && (
                <div>
                    <Button variant="outline" color="red" style={{ zIndex: 1001 }} onClick={handleCancel}>
                        Cancel
                    </Button>
                </div>
            )}

            <Stack>
                {UserGuide(title, description_userguide)}
                <NativeSelect
                    value={selectedModeOption}
                    onChange={(e) => setSelectedModeOption(e.target.value)}
                    title={"Attack mode"}
                    data={attackMode}
                    required
                    placeholder={"Pick a attack mode"}
                    label={"Attack mode, refer: https://hashcat.net/hashcat"}
                />
                <Grid>
                    <Grid.Col span={3}>
                        <NativeSelect
                            value={selectedInputOption}
                            onChange={(e) => setSelectedInputOption(e.target.value)}
                            label={"Input Hash Type"}
                            data={inputType}
                            required
                            placeholder={"Input type"}
                        />
                    </Grid.Col>
                    <Grid.Col span={9}>
                        <NumberInput
                            label={"Hash Algorithm, refer: https://hashcat.net/hashcat"}
                            placeholder={"Enter the Hash Algorithm code"}
                            required
                            {...form.getInputProps("hashAlgorithmCode")}
                        />
                    </Grid.Col>
                </Grid>
                {!isFile && (
                    <TextInput
                        label={"Input hash value"}
                        placeholder={"eg:ae71a4222ef1893879b442f14c40c370"}
                        required
                        {...form.getInputProps("hashValue")}
                    />
                )}
                {isFile && (
                    <TextInput
                        label={"Input hash file path"}
                        placeholder={" eg: /root/hash.txt"}
                        required
                        {...form.getInputProps("hashFilePath")}
                    />
                )}
                {isPasswordFile && (
                    <TextInput
                        label={"Input password file"}
                        placeholder={"eg: /root/pwd.txt"}
                        required
                        {...form.getInputProps("passwordFilePath")}
                    />
                )}
                {isCharset && (
                    <Grid>
                        <Grid.Col span={6}>
                            <NumberInput
                                label={"Minimum password length"}
                                placeholder={"Start from 1"}
                                required
                                {...form.getInputProps("minPwdLen")}
                            />
                        </Grid.Col>
                        <Grid.Col span={6}>
                            <NumberInput
                                label={"Maximum password length"}
                                placeholder={"Recommend not bigger than 8"}
                                required
                                {...form.getInputProps("maxPwdLen")}
                            />
                        </Grid.Col>
                    </Grid>
                )}
                {isCharset && (
                    <TextInput
                        label={"Mask Charsets, refer: https://hashcat.net/hashcat"}
                        placeholder={"eg: ?d?d?d?d"}
                        {...form.getInputProps("maskCharsets")}
                    />
                )}
                <TextInput
                    label={"Additional command, refer: https://hashcat.net/hashcat"}
                    placeholder={"eg: --force"}
                    {...form.getInputProps("additionalCommand")}
                />
                <Alert
                    icon={<IconAlertCircle size={16} />}
                    radius="md"
                    children={
                        "Please try with additional command '--force', otherwise you have to download OpenCL for hashcat. "
                    }
                ></Alert>
                <Button type={"submit"}>Crack</Button>
                {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
                <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
            </Stack>
        </form>
    );
};

export default Hashcat;
