import { Button, LoadingOverlay, Stack, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { useCallback, useState } from "react";
import { CommandHelper } from "../../utils/CommandHelper";
import ConsoleWrapper from "../ConsoleWrapper/ConsoleWrapper";
import { UserGuide } from "../UserGuide/UserGuide";
import { LoadingOverlayAndCancelButton } from "../OverlayAndCancelButton/OverlayAndCancelButton";
import { SaveOutputToTextFile } from "../SaveOutputToFile/SaveOutputToTextFile";

const title = "Parsero";
const description =
    "Parsero is a free script written in Python which reads the Robots.txt file of a web server and looks at the Disallow entries." +
    "The Disallow entries tell the search engines what directories or files hosted on a web server mustn’t be indexed. " +
    "\n\nParsero Reference Guide: https://www.kali.org/tools/parsero/ \n\n" +
    "How to use Parsero:\n\n" +
    "Step 1: Enter an URL.\n" +
    "       E.g. www.google.com\n\n" +
    "Step 2: Click Start Parsero" +
    "\n\n Step 3 : View Results";
interface FormValues {
    url: string;
}

const Parsero = () => {
    const [pid, setPid] = useState("");
    const [loading, setLoading] = useState(false);
    const [output, setOutput] = useState("");
    let form = useForm({
        initialValues: {
            url: "",
        },
    });
    // Uses the callback function of runCommandGetPidAndOutput to handle and save data
    // generated by the executing process into the output state variable.
    const handleProcessData = useCallback((data: string) => {
        setOutput((prevOutput) => prevOutput + "\n" + data); // Update output
    }, []);

    // Uses the onTermination callback function of runCommandGetPidAndOutput to handle
    // the termination of that process, resetting state variables, handling the output data,
    // and informing the user.
    const handleProcessTermination = useCallback(
        ({ code, signal }: { code: number; signal: number }) => {
            if (code === 0) {
                handleProcessData("\nProcess completed successfully.");
            } else if (signal === 15) {
                handleProcessData("\nProcess was manually terminated.");
            } else {
                handleProcessData(`\nProcess terminated with exit code: ${code} and signal code: ${signal}`);
            }
            // Clear the child process pid reference
            setPid("");
            // Cancel the Loading Overlay
            setLoading(false);
        },
        [handleProcessData]
    );

    const onSubmit = async (values: FormValues) => {
        setLoading(true);

        const args = [`-u`, values.url];
        try {
            const result = await CommandHelper.runCommandGetPidAndOutput(
                "parsero",
                args,
                handleProcessData,
                handleProcessTermination
            );
            setPid(result.pid);
            setOutput(result.output);
        } catch (e: any) {
            setOutput(e.message);
        }
    };

    const clearOutput = useCallback(() => {
        setOutput("");
    }, [setOutput]);

    return (
        <form onSubmit={form.onSubmit(onSubmit)}>
            {LoadingOverlayAndCancelButton(loading, pid)}
            <Stack>
                {UserGuide(title, description)}
                <TextInput label={"url"} required {...form.getInputProps("url")} />
                <Button type={"submit"}>Start parsero</Button>
                {SaveOutputToTextFile(output)}
                <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
            </Stack>
        </form>
    );
};
export default Parsero;
