import { Button, LoadingOverlay, Stack, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { useCallback, useState } from "react";
import { CommandHelper } from "../../utils/CommandHelper";
import ConsoleWrapper from "../ConsoleWrapper/ConsoleWrapper";
import { UserGuide } from "../UserGuide/UserGuide";
import { SaveOutputToTextFile_v2 } from "../SaveOutputToFile/SaveOutputToTextFile";
import { LoadingOverlayAndCancelButton } from "../OverlayAndCancelButton/OverlayAndCancelButton";

const title = "Crunch Password Generator";
const description_userguide =
    "Crunch is a wordlist generator where you can specify a standard character set or a custom one based on the " +
    "needs of your project. Crunch can create a wordlist based on criteria you specify. The wordlist can be " +
    "used for various purposes such as dictionary attacks or password cracking.\n\nYou can find more information " +
    "about the tool, including usage instructions and examples, in its official documentation: https://tools.kali." +
    "org/password-attacks/crunch\n\n" +
    "Using Crunch:\n" +
    "Step 1: Enter a Minimum password length.\n" +
    "       Eg: 8\n\n" +
    "Step 2: Enter a Maximum password length.\n" +
    "       Eg: 8\n\n" +
    "Step 3: Enter a Character set for the password generation.\n" +
    "       Eg: abcdefghijklmnopqrstuvwxyz123456789\n\n" +
    "Step 4: (Optional) Enter the directory for an Output file.\n\n" +
    "Step 5: Click Generate Password List to commence Crunch's operation.\n\n" +
    "Step 6: View the Output block below to view the results of the tools execution.";

//list of input values collected by the form
interface FormValuesType {
    minLength: number;
    maxLength: number;
    charset: string;
    outputFile: string;
}

const Crunch = () => {
    //sets the state of the tool; loading or not, what the output is
    const [loading, setLoading] = useState(false);
    const [output, setOutput] = useState("");
    const [pid, setPid] = useState("");
    const [allowSave, setAllowSave] = useState(false);
    const [hasSaved, setHasSaved] = useState(false);

    //initial form values
    //Update initial value for minLength = 3, maxLength = 4, charset = abcde
    //If use select the current initial values the execution time will be very long
    let form = useForm({
        initialValues: {
            minLength: 3,
            maxLength: 4,
            charset: "abcde",
            outputFile: "",
        },
    });

    // Uses the callback function of runCommandGetPidAndOutput to handle and save data
    // generated by the executing process into the output state variable.
    const handleProcessData = useCallback((data: string) => {
        setOutput((prevOutput) => prevOutput + "\n" + data); // Update output
    }, []);

    // Uses the onTermination callback function of runCommandGetPidAndOutput to handle
    // the termination of that process, resetting state variables, handling the output data,
    // and informing the user.
    const handleProcessTermination = useCallback(
        ({ code, signal }: { code: number; signal: number }) => {
            if (code === 0) {
                handleProcessData("\nProcess completed successfully.");
            } else if (signal === 15) {
                handleProcessData("\nProcess was manually terminated.");
            } else {
                handleProcessData(`\nProcess terminated with exit code: ${code} and signal code: ${signal}`);
            }
            // Clear the child process pid reference
            setPid("");
            // Cancel the Loading Overlay
            setLoading(false);

            // Allow Saving as the output is finalised
            setAllowSave(true);
            setHasSaved(false);
        },
        [handleProcessData]
    );

    // Actions taken after saving the output
    const handleSaveComplete = () => {
        // Indicating that the file has saved which is passed
        // back into SaveOutputToTextFile to inform the user
        setHasSaved(true);
        setAllowSave(false);
    };

    //sets the loading state to True, provides arguments for the tool
    const onSubmit = async (values: FormValuesType) => {
        // Disallow saving until the tool's execution is complete
        setAllowSave(false);

        setLoading(true);

        const args = [`${values.minLength}`, `${values.maxLength}`, `${values.charset}`];

        //pushes the output file argument if one is provided by user
        if (values.outputFile) {
            args.push("-o", values.outputFile);
        }

        try {
            const result = await CommandHelper.runCommandGetPidAndOutput(
                "crunch",
                args,
                handleProcessData,
                handleProcessTermination
            );
            setPid(result.pid);
            setOutput(result.output);
        } catch (e: any) {
            setOutput(e.message);
        }
    };

    //clears output without completely refreshing the tool
    const clearOutput = useCallback(() => {
        setOutput("");
        setHasSaved(false);
        setAllowSave(false);
    }, [setOutput]);

    return (
        //define user interface of the tool
        <form onSubmit={form.onSubmit(onSubmit)}>
            {LoadingOverlayAndCancelButton(loading, pid)}
            <LoadingOverlay visible={loading} />
            <Stack>
                {UserGuide(title, description_userguide)}
                <TextInput
                    label={"Minimum password length"}
                    type="number"
                    min={1}
                    required
                    {...form.getInputProps("minLength")}
                />
                <TextInput
                    label={"Maximum password length"}
                    type="number"
                    min={1}
                    required
                    {...form.getInputProps("maxLength")}
                />
                <TextInput
                    label={"Character set (e.g. abcdefghijklmnopqrstuvwxyz0123456789)"}
                    required
                    {...form.getInputProps("charset")}
                />
                <TextInput label={"Output file (optional)"} {...form.getInputProps("outputFile")} />
                <Button type={"submit"}>Generate Password List</Button>
                {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
                <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
            </Stack>
        </form>
    );
};

export default Crunch;
