name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    dependencies:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        strategy:
            matrix:
                node-version: [20]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Install dependencies
              run: npm install

    style:
        runs-on: ubuntu-latest
        needs: dependencies

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - run: npm install

            - name: Run style check
              run: npm run style

    test:
        runs-on: ubuntu-latest
        needs: dependencies

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - run: npm install

            - name: Run tests
              run: npm run test

    security_test:
        runs-on: ubuntu-latest
        needs: dependencies

        steps:
            - uses: actions/checkout@v4

            - name: Run Trivy scanner
              uses: aquasecurity/trivy-action@0.33.1
              with:
                  scan-type: fs
                  ignore-unfixed: true
                  format: table
                  severity: HIGH,CRITICAL
                  exit-code: 1

            - name: Run TruffleHog scan
              run: |
                  docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github \
                  --repo https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit \
                  --only-verified

    build:
        runs-on: ubuntu-latest
        needs: dependencies

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - run: npm install

            - name: Build project
              run: npm run build
