name: Release

on:
    push:
        branches:
            - "release"

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Install Dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Build Tauri
            - run: yarn && yarn build
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: "App v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: false
                  prerelease: false
    update:
        needs: release
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - run: yarn

            - name: Create Update
              run: yarn update
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
